### ISSUE TITLE
New article to show options for the _pkgdown.yml setup 

### ISSUE THREAD

**Issue by maurolepore** [maurolepore/dverse#24]
* [At the top of Packages](https://github.com/maurolepore/pactaverse/blob/global-search/_pkgdown.yml)
* [Overwriting Reference/](https://github.com/forestgeo/fgeo/blob/master/_pkgdown.yml)
* Other?

**Comment by maurolepore** [comment]
The trick is this

```yaml
navbar:
  type: default
  left:
  - text: "Reference"
    href: articles/reference.html
```

[Example](https://github.com/maurolepore/admiralverse/blob/main/_pkgdown.yml) covered by:

* [Creating the (toy) 'admiralverse' meta-package](https://youtu.be/ezVpsadSF7A?si=_aDAZ_a4ErJ9Usjw)
* [Creating a website for the (toy) 'admiralverse' with a global search](https://youtu.be/VhmnADBDXv0?si=DHszgf4vBsIURTX9)
